[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"

[build.environment]
  STATUSKIT_PAGE_TITLE = "GitKraken Status"
  STATUSKIT_COMPANY_LOGO = "https://www.gitkraken.com/downloads/brand-assets/gitkraken-keif-teal-sq.png"
  STATUSKIT_SUPPORT_CONTACT_LINK = "https://www.gitkraken.com/contact"
  STATUSKIT_RESOURCES_LINK = "https://support.gitkraken.com/"
  
